Feat/bpo display name order
bonitasoft/bonita-web-pages pull request #437
Opened 2020-11-03 10:57 UTC by VishalThapaliya

- Show the "display name" first and then the "name" on the page as well as in the sorting options (if possible).
- Admin process list
- Admin task list
- Admin group list
- Admin task details
- Admin case details

Covers [BPO-569](https://bonitasoft.atlassian.net/browse/BPO-569)

2020-11-06 16:44 UTC, abirembaut requested changes
Just one comment
Other than that it looks good to me

2020-11-06 16:44 UTC, abirembaut commented on uid-pages/page-admin-case-details/src/adminCaseDetailsBonitaV1.json
> +                        "value" : "Display name"
should be Process display name

2020-11-09 14:15 UTC, abirembaut approved these changes

2020-11-09 15:09 UTC, DumitruCorini approved these changes

2020-11-09 16:38 UTC, merged