Create user confirmation message
bonitasoft/bonita-web-pages pull request #451
Opened 2020-11-17 10:58 UTC by VishalThapaliya

Display success message when create or update a user.

Covers [BR-583](https://bonitasoft.atlassian.net/browse/BR-583)

2020-11-18 09:50 UTC, DumitruCorini requested changes
Also, why do you have both hasRecentlyBeenActivated and hasRecentlyBeenDeactivated? Both are used in the same way, could we not just keep one and it would work all the same?

2020-11-18 09:50 UTC, DumitruCorini commented on uid-pages/page-admin-user-list/src/adminUserListBonitaV1.json
> +        "    $data.changeStatusData.hasRecentlyBeenDeactivated === true;",
This seems weird, why are we verifying that hasRecentlyBeenDeactivated is equal to true?

2020-11-18 18:16 UTC, abirembaut approved these changes
LGTM

2020-11-19 09:26 UTC, DumitruCorini commented on uid-pages/page-admin-user-list/src/adminUserListBonitaV1.json
> +        "    $data.changeStatusData.hasRecentlyBeenDeactivated === true;",
Done

2020-11-19 09:26 UTC, DumitruCorini approved these changes

2020-11-19 14:11 UTC, merged